name: logfmt
arguments:
  circleAPIKey: 2b5e5793e375e5a6ddf98251848372496e943192
  commands:
    - logfmt
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: Development time log formatter. Helps format structured logs to a human readable format.
  go-protoc-imports: []
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  metrics: datadog
  opslevel:
    confluenceSpaceKey: DTSS
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
    prereleasesBranch: ""
  reportingTeam: fnd-dt
  resources: {}
  service: false
  slack: dev-tooling-notifications
  terraform:
    datadog:
      grpc:
        evaluationWindow: ""
        latency:
          percentiles:
            highTraffic: 0
            lowTraffic: 0
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        lowTrafficCountThreshold: 0
        qos:
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        tags: []
      http:
        evaluationWindow: ""
        percentiles:
          highTraffic: 0
          lowTraffic: 0
        thresholds:
          highTraffic: 0
          lowCount: 0
          lowTraffic: 0
      pods:
        thresholds:
          availableLowCount: 0
  tracing: opentelemetry
  tutorial: false
  validation: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-discovery
migrated: true
