name: logfmt
arguments:
  circleAPIKey: 2b5e5793e375e5a6ddf98251848372496e943192
  ciOptions:
    skipE2e: true
    skipDocker: true
  commands:
    - logfmt
  description: Development time log formatter. Helps format structured logs to a human readable format.
  lintroller: platinum
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
  reportingTeam: fnd-dt
  service: false
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-discovery
