name: logfmt
reportingTeam: fnd-dt
description: Development time log formatter. Helps format structured logs to a human readable format.
oss: true
slack: dev-tooling-notifications
library: true
commands:
  - logfmt
circleAPIKey: 2b5e5793e375e5a6ddf98251848372496e943192
lintroller: platinum
tracing: honeycomb
metrics: datadog
releaseType: semver
releaseOptions:
  allowPrereleases: true
  allowMajorVersions: true
deployTo:
  environments: []
arguments:
  circleAPIKey: 2b5e5793e375e5a6ddf98251848372496e943192
  commands:
    - logfmt
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: Development time log formatter. Helps format structured logs to a human readable format.
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  metrics: datadog
  opslevel:
    confluenceSpaceKey: DTSS
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: true
    enablePrereleases: true
  reportingTeam: fnd-dt
  resources: {}
  service: false
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-opslevel
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
